import type { Metadata } from "next";
import LeftBar from "@/components/dashboard/LeftSideBar";
import "../globals.css";
import DashboardTopBar from "@/components/dashboard/TopBar";
import DashboardBottomBar from "@/components/dashboard/BottomBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <DashboardTopBar />
      <main className="flex flex-row">
        <LeftBar />
        <section className="flex min-h-screen flex-1 items-center flex-col px-6 pt-28 pb-10 sm:px-10 max-md:mb-20">
          <div className="w-full max-w-4xl">{children}</div>
        </section>
      </main>
      <DashboardBottomBar />
    </div>
  );
}
