import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "FlowFund",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full flex items-center min-h-screen justify-center">
      {children}
    </main>
  );
}
